name: 'pr-diff-contains'
description: 'Fails if the PR diff contains certain words'
author: 'Freetrade'
inputs:
  words:
    required: true
    description: 'a list of words to check in the PR diff'
runs:
  using: 'node12'
  main: 'dist/index.js'
